USE sgbd_system;

DROP TABLE IF EXISTS disciplinas;

CREATE TABLE disciplinas (
    id INT(11) UNSIGNED AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
);